name: number_format_ext
description: Numberformat extnsion, Added floor and ceil methods to Numberformat.
version: 1.5.0
repository: https://github.com/xyqjay/number_format_ext

environment:
  sdk: ^3.0.0

dependencies:
  decimal: ^1.5.0
  intl: ^0.19.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
