name: number_format_ext
description: Numberformat extnsion, Added floor and ceil methods to Numberformat.
version: 2.3.3
repository: https://github.com/xyqjay/number_format_ext

environment:
  sdk: ^3.0.0

dependencies:
  decimal: ^2.3.3
  intl: ^0.19.0
  rational: ^2.2.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
